# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

 name: MavenBuild

 on:
   push:
     branches: [main]

 jobs:   
   build:
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2
       with:
         fetch-depth: "0"
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
         java-version: "11"
         distribution: "adopt"
         #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
         #settings-path: ${{ github.workspace }} # location for the settings.xml file
     
     - name: Determine Tag
       id: DetermineTag
       uses: anothrNick/github-tag-action@1.38.0
       env:
         GITHUB_TOKEN: ${{ secrets.token }}
     
  #   - name: get version
   #    run: echo "${{ steps.DetermineTag.outputs.tag }}"
     - name: update and build
       run: |
         mvn versions:set -DnewVersion=${{ steps.versioning.outputs.tag }}
         mvn --batch-mode --update-snapshots package
   #  - name: Build with Maven
       #run: mvn -B package --file pom.xml
     #  run: mvn --batch-mode --update-snapshots package

     - name: Publish to GitHub Packages Apache Maven
       #run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
       run: mvn --batch-mode deploy
       env:
         GITHUB_TOKEN: ${{ secrets.token }}

     - name: Create a Release
       uses: elgohr/Github-Release-Action@v4
       env:
         GITHUB_TOKEN: ${{ secrets.token }}
       with:
         title: ${{ steps.DetermineTag.outputs.tag }}
